// <auto-generated />
namespace PaginaWebGaes23.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hoy1234 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hoy1234));
        
        string IMigrationMetadata.Id
        {
            get { return "202105292107118_hoy1234"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
